// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDZ6lea3HfYNHHk56a6XjfyklgXNmKi1EU',
//     appId: '1:558343760209:web:40cdf70d0e292a66800b70',
//     messagingSenderId: '558343760209',
//     projectId: 'provasdelaco',
//     authDomain: 'provasdelaco.firebaseapp.com',
//     storageBucket: 'provasdelaco.firebasestorage.app',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCttqpQ_-pKp-Wqcqmog8A_koxL93xty2A',
//     appId: '1:558343760209:android:5ec2d882a0083648800b70',
//     messagingSenderId: '558343760209',
//     projectId: 'provasdelaco',
//     storageBucket: 'provasdelaco.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBFMUd4r7m_TOlAizmspnv3F_FDBozZaEI',
//     appId: '1:558343760209:ios:38d0cff35e2125de800b70',
//     messagingSenderId: '558343760209',
//     projectId: 'provasdelaco',
//     storageBucket: 'provasdelaco.firebasestorage.app',
//     androidClientId: '558343760209-hujctapi6sdgnfvc560q3stpblbnrt7v.apps.googleusercontent.com',
//     iosClientId: '558343760209-otkb4vfkk0rps1t5lgga4sjgpikmobf4.apps.googleusercontent.com',
//     iosBundleId: 'com.provadelaco.glauber',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBFMUd4r7m_TOlAizmspnv3F_FDBozZaEI',
//     appId: '1:558343760209:ios:5f457c0349d2c881800b70',
//     messagingSenderId: '558343760209',
//     projectId: 'provasdelaco',
//     storageBucket: 'provasdelaco.firebasestorage.app',
//     androidClientId: '558343760209-hujctapi6sdgnfvc560q3stpblbnrt7v.apps.googleusercontent.com',
//     iosClientId: '558343760209-kli5es5ed4fft96osjb5b3kru421qv43.apps.googleusercontent.com',
//     iosBundleId: 'com.example.glauber',
//   );

// }